"use client";

import { useEffect, useRef, useState } from "react";
import { motion, animate } from "framer-motion";

// ─── Constants ────────────────────────────────────────────────────────────────

const INSTALLED_MW      = 40;
const CAPACITY_FACTOR   = 0.21;
const KWH_PER_SECOND    = (INSTALLED_MW * 1_000 * CAPACITY_FACTOR) / 3600; // ~2.333 kWh/s
const FALLBACK_ISO      = "2024-01-01T00:00:00Z";

function hoursElapsed(isoDate: string): number {
  const ms = Date.now() - new Date(isoDate).getTime();
  return Math.max(0, ms / 3_600_000);
}

function baseKwh(isoDate: string): number {
  return INSTALLED_MW * 1_000 * CAPACITY_FACTOR * hoursElapsed(isoDate);
}

const fmt = new Intl.NumberFormat("en-IN", { maximumFractionDigits: 0 });

// ─── Component ────────────────────────────────────────────────────────────────

export default function LiveGenerationCounter({
  plantSinceISO = FALLBACK_ISO,
}: {
  plantSinceISO?: string;
}) {
  const [count, setCount]     = useState<number>(() => baseKwh(plantSinceISO));
  const [modal, setModal]     = useState(false);
  const [pulse, setPulse]     = useState(false);
  const intervalRef           = useRef<ReturnType<typeof setInterval> | null>(null);
  const pulseRef              = useRef<ReturnType<typeof setInterval> | null>(null);

  // Increment every second
  useEffect(() => {
    intervalRef.current = setInterval(() => {
      setCount((c) => c + KWH_PER_SECOND);
    }, 1_000);
    return () => clearInterval(intervalRef.current!);
  }, []);

  // Pulse every 5 seconds
  useEffect(() => {
    pulseRef.current = setInterval(() => {
      setPulse(true);
      setTimeout(() => setPulse(false), 800);
    }, 5_000);
    return () => clearInterval(pulseRef.current!);
  }, []);

  // Close modal on Escape
  useEffect(() => {
    if (!modal) return;
    const handler = (e: KeyboardEvent) => { if (e.key === "Escape") setModal(false); };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [modal]);

  return (
    <>
      {/* ── Band ─────────────────────────────────────────────────────────── */}
      <section className="bg-kmpr-navy py-16 w-full">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="text-kmpr-teal text-xs font-semibold uppercase tracking-widest mb-5">
            Live Generation
          </p>

          <p className="text-white/60 text-sm mb-4">
            Units generated by KMPR since launch:
          </p>

          {/* Clickable counter */}
          <button
            onClick={() => setModal(true)}
            aria-label="Learn how this number is calculated"
            className="group focus:outline-none"
          >
            <motion.span
              animate={pulse ? { scale: [1, 1.04, 1] } : {}}
              transition={{ duration: 0.6, ease: "easeInOut" }}
              className="inline-block tabular text-5xl sm:text-6xl lg:text-7xl font-bold text-kmpr-teal leading-none group-hover:text-white transition-colors"
            >
              {fmt.format(Math.floor(count))}
            </motion.span>
          </button>

          <p className="text-white/50 text-base mt-3">
            kWh — and counting.
          </p>

          <p className="text-white/25 text-xs mt-5">
            Click the number to see how it&apos;s calculated.
          </p>
        </div>
      </section>

      {/* ── Modal ────────────────────────────────────────────────────────── */}
      {modal && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="Generation formula"
          className="fixed inset-0 z-50 flex items-center justify-center p-4"
        >
          {/* Backdrop */}
          <div
            className="absolute inset-0 bg-black/60 backdrop-blur-sm"
            onClick={() => setModal(false)}
          />

          {/* Panel */}
          <div className="relative bg-white rounded-2xl shadow-2xl max-w-md w-full p-8 z-10">
            <button
              onClick={() => setModal(false)}
              className="absolute top-4 right-4 text-kmpr-muted hover:text-kmpr-navy transition-colors"
              aria-label="Close"
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18 18 6M6 6l12 12" />
              </svg>
            </button>

            <p className="text-kmpr-teal text-xs font-semibold uppercase tracking-widest mb-2">
              How we calculate this
            </p>
            <h3 className="text-xl font-bold text-kmpr-navy mb-5">
              Generation formula
            </h3>

            <div className="bg-kmpr-soft-bg rounded-xl p-5 font-mono text-xs text-kmpr-navy leading-relaxed mb-5">
              <p className="text-kmpr-muted mb-1">// per-second rate</p>
              <p>kWh/s = 40 MW × 1,000 × 0.21 ÷ 3,600</p>
              <p className="mt-2 text-kmpr-muted mb-1">// cumulative</p>
              <p>total = kWh/s × seconds since commissioning</p>
            </div>

            <div className="space-y-2 text-sm text-kmpr-text">
              <div className="flex justify-between">
                <span className="text-kmpr-muted">Installed capacity</span>
                <span className="font-semibold text-kmpr-navy">40 MW</span>
              </div>
              <div className="flex justify-between">
                <span className="text-kmpr-muted">Capacity factor</span>
                <span className="font-semibold text-kmpr-navy">21%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-kmpr-muted">kWh per second</span>
                <span className="font-semibold text-kmpr-teal tabular">≈ {KWH_PER_SECOND.toFixed(3)}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-kmpr-muted">Plant commissioned</span>
                <span className="font-semibold text-kmpr-navy tabular">
                  {new Date(plantSinceISO).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}
                </span>
              </div>
            </div>

            <p className="text-kmpr-muted text-xs mt-5 pt-4 border-t border-kmpr-teal/10 leading-relaxed">
              Source: SLDC monthly settlement (simulation between settlements).
              Actual generation may vary by ±5% due to grid curtailment and maintenance windows.
            </p>
          </div>
        </div>
      )}
    </>
  );
}
